name: Posting Daily X Post

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install Dependencies
        working-directory: ./Server/x_server
        run: pnpm install

      - name: Create a Post
        working-directory: ./Server/x_server
        run: pnpm ts-node x_autoposting.ts
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
